Allow Object.entries (only for type checks, this is not a polyfill). Fixes the error:
> tsc
components/progress/Line.tsx:21:37 - error TS2339: Property 'entries' does not exist on type 'ObjectConstructor'.

21   for (const [key, value] of Object.entries(gradients)) {
                                       ~~~~~~~
Found 1 error.

Object.entries is used in components/progress/Line.tsx.